name: book
channels:
  - conda-forge
dependencies:
  - jupyter-book=1
  - xeus-octave
  - octave
  - python=3.12
  - jupyterlab
  - ipywidgets
  - fortran-compiler
  - cxx-compiler
  - poppler
  - control
  - pip:
      - ghp-import
      - jupyter-matlab-proxy
      - sphinxemoji
      - jupyter-tikz
      - jupyterlab_myst
